import type { AITool, Prompt, Category, Creator } from '@/types';

export const aiTools: AITool[] = [
  { id: 'chatgpt', name: 'ChatGPT', logo: '/tools/chatgpt.svg', color: '#10a37f', promptCount: 12543 },
  { id: 'midjourney', name: 'Midjourney', logo: '/tools/midjourney.svg', color: '#000000', promptCount: 8932 },
  { id: 'dalle', name: 'DALL-E', logo: '/tools/dalle.svg', color: '#10a37f', promptCount: 5621 },
  { id: 'stable-diffusion', name: 'Stable Diffusion', logo: '/tools/sd.svg', color: '#5B47FB', promptCount: 7845 },
  { id: 'claude', name: 'Claude', logo: '/tools/claude.svg', color: '#CC9B7A', promptCount: 3421 },
  { id: 'gemini', name: 'Gemini', logo: '/tools/gemini.svg', color: '#4285f4', promptCount: 2156 },
  { id: 'runway', name: 'Runway', logo: '/tools/runway.svg', color: '#00D4FF', promptCount: 1823 },
  { id: 'elevenlabs', name: 'ElevenLabs', logo: '/tools/elevenlabs.svg', color: '#000000', promptCount: 1245 },
];

export const categories: Category[] = [
  {
    id: 'text-ai',
    name: 'Text & Chat AI',
    icon: '💬',
    description: 'ChatGPT, Claude, Gemini prompts',
    promptCount: 15234,
    color: 'from-emerald-500 to-teal-600',
    bgColor: 'bg-emerald-500/10',
  },
  {
    id: 'image-ai',
    name: 'Image Generation',
    icon: '🎨',
    description: 'Midjourney, DALL-E, Stable Diffusion',
    promptCount: 12567,
    color: 'from-violet-500 to-purple-600',
    bgColor: 'bg-violet-500/10',
  },
  {
    id: 'video-ai',
    name: 'Video Generation',
    icon: '🎬',
    description: 'Runway, Pika, Sora prompts',
    promptCount: 3892,
    color: 'from-rose-500 to-pink-600',
    bgColor: 'bg-rose-500/10',
  },
  {
    id: 'audio-ai',
    name: 'Audio & Voice',
    icon: '🎤',
    description: 'ElevenLabs, voice synthesis',
    promptCount: 2156,
    color: 'from-amber-500 to-orange-600',
    bgColor: 'bg-amber-500/10',
  },
  {
    id: 'code-ai',
    name: 'Code & Development',
    icon: '💻',
    description: 'GitHub Copilot, coding assistants',
    promptCount: 5432,
    color: 'from-blue-500 to-indigo-600',
    bgColor: 'bg-blue-500/10',
  },
  {
    id: 'business-ai',
    name: 'Business & Marketing',
    icon: '📊',
    description: 'SEO, copywriting, ads',
    promptCount: 8976,
    color: 'from-cyan-500 to-sky-600',
    bgColor: 'bg-cyan-500/10',
  },
];

export const trendingPrompts: Prompt[] = [
  {
    id: '1',
    title: 'Ultimate ChatGPT Prompt for Business Growth Strategies',
    thumbnail: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=400&h=300&fit=crop',
    price: 4.99,
    isFree: false,
    rating: 4.9,
    reviews: 234,
    sales: 1520,
    views: 8932,
    seller: { name: 'PromptMaster', avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=48&h=48&fit=crop', verified: true },
    tool: { name: 'ChatGPT', logo: '/tools/chatgpt.svg' },
    category: 'Business',
    description: 'A comprehensive prompt template for generating detailed business growth strategies using ChatGPT.',
  },
  {
    id: '2',
    title: 'Midjourney Portrait Master - Photorealistic Human Faces',
    thumbnail: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&h=300&fit=crop',
    price: 9.99,
    isFree: false,
    rating: 4.8,
    reviews: 189,
    sales: 987,
    views: 5432,
    seller: { name: 'AI Artist Pro', avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=48&h=48&fit=crop', verified: true },
    tool: { name: 'Midjourney', logo: '/tools/midjourney.svg' },
    category: 'Image Generation',
    description: 'Create stunning photorealistic portraits with this advanced Midjourney prompt template.',
  },
  {
    id: '3',
    title: 'Free DALL-E Logo Design Prompt Pack',
    thumbnail: 'https://images.unsplash.com/photo-1626785774573-4b799315345d?w=400&h=300&fit=crop',
    price: 0,
    isFree: true,
    rating: 4.7,
    reviews: 456,
    sales: 3421,
    views: 12453,
    seller: { name: 'DesignWizard', avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=48&h=48&fit=crop' },
    tool: { name: 'DALL-E', logo: '/tools/dalle.svg' },
    category: 'Design',
    description: 'Free logo design prompts for DALL-E. Perfect for startups and small businesses.',
  },
  {
    id: '4',
    title: 'Claude Code Review Assistant Prompt',
    thumbnail: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=400&h=300&fit=crop',
    price: 2.99,
    isFree: false,
    rating: 4.9,
    reviews: 123,
    sales: 756,
    views: 3421,
    seller: { name: 'CodeNinja', avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=48&h=48&fit=crop', verified: true },
    tool: { name: 'Claude', logo: '/tools/claude.svg' },
    category: 'Code',
    description: 'Expert code review prompts for Claude AI. Improve your code quality instantly.',
  },
  {
    id: '5',
    title: 'Stable Diffusion Fantasy Landscapes',
    thumbnail: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=400&h=300&fit=crop',
    price: 7.99,
    isFree: false,
    rating: 4.8,
    reviews: 267,
    sales: 1234,
    views: 6789,
    seller: { name: 'FantasyAI', avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=48&h=48&fit=crop' },
    tool: { name: 'Stable Diffusion', logo: '/tools/sd.svg' },
    category: 'Image Generation',
    description: 'Create breathtaking fantasy landscapes with detailed prompt engineering.',
  },
  {
    id: '6',
    title: 'ChatGPT Marketing Copy Generator',
    thumbnail: 'https://images.unsplash.com/photo-1533750349088-cd871a92f312?w=400&h=300&fit=crop',
    price: 5.99,
    isFree: false,
    rating: 4.6,
    reviews: 345,
    sales: 1876,
    views: 8765,
    seller: { name: 'MarketingGuru', avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=48&h=48&fit=crop', verified: true },
    tool: { name: 'ChatGPT', logo: '/tools/chatgpt.svg' },
    category: 'Marketing',
    description: 'Generate compelling marketing copy for any product or service.',
  },
  {
    id: '7',
    title: 'Runway Video Transition Pack',
    thumbnail: 'https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=400&h=300&fit=crop',
    price: 12.99,
    isFree: false,
    rating: 4.9,
    reviews: 89,
    sales: 432,
    views: 2341,
    seller: { name: 'VideoMaster', avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=48&h=48&fit=crop' },
    tool: { name: 'Runway', logo: '/tools/runway.svg' },
    category: 'Video',
    description: 'Professional video transition prompts for Runway Gen-2.',
  },
  {
    id: '8',
    title: 'Free ElevenLabs Voiceover Scripts',
    thumbnail: 'https://images.unsplash.com/photo-1590602847861-f357a9332bbc?w=400&h=300&fit=crop',
    price: 0,
    isFree: true,
    rating: 4.5,
    reviews: 234,
    sales: 1567,
    views: 5432,
    seller: { name: 'VoicePro', avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=48&h=48&fit=crop' },
    tool: { name: 'ElevenLabs', logo: '/tools/elevenlabs.svg' },
    category: 'Audio',
    description: 'Free voiceover script templates optimized for ElevenLabs AI voices.',
  },
];

export const creators: Creator[] = [
  {
    id: '1',
    name: 'PromptMaster',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=80&h=80&fit=crop',
    verified: true,
    rating: 4.9,
    sales: 15234,
    prompts: 156,
    topCategory: 'ChatGPT',
  },
  {
    id: '2',
    name: 'AI Artist Pro',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=80&h=80&fit=crop',
    verified: true,
    rating: 4.8,
    sales: 12345,
    prompts: 89,
    topCategory: 'Midjourney',
  },
  {
    id: '3',
    name: 'CodeNinja',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=80&h=80&fit=crop',
    verified: true,
    rating: 4.9,
    sales: 9876,
    prompts: 234,
    topCategory: 'Code',
  },
  {
    id: '4',
    name: 'DesignWizard',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=80&h=80&fit=crop',
    verified: false,
    rating: 4.7,
    sales: 8765,
    prompts: 67,
    topCategory: 'Design',
  },
  {
    id: '5',
    name: 'MarketingGuru',
    avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=80&h=80&fit=crop',
    verified: true,
    rating: 4.8,
    sales: 7654,
    prompts: 123,
    topCategory: 'Marketing',
  },
  {
    id: '6',
    name: 'FantasyAI',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=80&h=80&fit=crop',
    verified: false,
    rating: 4.6,
    sales: 6543,
    prompts: 45,
    topCategory: 'Image Generation',
  },
  {
    id: '7',
    name: 'VideoMaster',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=80&h=80&fit=crop',
    verified: true,
    rating: 4.9,
    sales: 5432,
    prompts: 78,
    topCategory: 'Video',
  },
  {
    id: '8',
    name: 'VoicePro',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=80&h=80&fit=crop',
    verified: false,
    rating: 4.5,
    sales: 4321,
    prompts: 56,
    topCategory: 'Audio',
  },
  {
    id: '9',
    name: 'StoryWeaver',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=80&h=80&fit=crop',
    verified: true,
    rating: 4.8,
    sales: 3456,
    prompts: 92,
    topCategory: 'ChatGPT',
  },
  {
    id: '10',
    name: 'PixelPerfect',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=80&h=80&fit=crop',
    verified: false,
    rating: 4.7,
    sales: 2876,
    prompts: 34,
    topCategory: 'Design',
  },
];

export const navItems = [
  {
    label: 'Categories',
    href: '/categories',
    children: [
      { label: 'Text & Chat AI', href: '/categories/text-ai', icon: '💬' },
      { label: 'Image Generation', href: '/categories/image-ai', icon: '🎨' },
      { label: 'Video Generation', href: '/categories/video-ai', icon: '🎬' },
      { label: 'Audio & Voice', href: '/categories/audio-ai', icon: '🎤' },
      { label: 'Code & Development', href: '/categories/code-ai', icon: '💻' },
      { label: 'Business & Marketing', href: '/categories/business-ai', icon: '📊' },
    ],
  },
  {
    label: 'AI Tools',
    href: '/tools',
    children: [
      { label: 'ChatGPT', href: '/tools/chatgpt', icon: '🤖' },
      { label: 'Midjourney', href: '/tools/midjourney', icon: '🎨' },
      { label: 'DALL-E', href: '/tools/dalle', icon: '🖼️' },
      { label: 'Stable Diffusion', href: '/tools/stable-diffusion', icon: '🎭' },
      { label: 'Claude', href: '/tools/claude', icon: '🧠' },
      { label: 'View All Tools', href: '/tools', icon: '→' },
    ],
  },
  { label: 'Trending', href: '/trending' },
  { label: 'Sell', href: '/sell' },
];
